version: "3.8"

services:
  backend:
    build: .
    container_name: express_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/bootCampApp"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
  
  
volumes:
  mongo-data:
